services:
  - type: web
    name: brvm-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    rootDir: .
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGO_URI
      - key: BRVM_URL
        value: https://www.brvm.org/...
      - key: RICHBOURSE_URL
        value: https://www.richbourse.com/...
